/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/layouts/AppLayout.vue')['default']
    AppNavbar: typeof import('./src/components/app/AppNavbar.vue')['default']
    AuctionUsernames: typeof import('./src/components/auction/AuctionUsernames.vue')['default']
    DefaultLayout: typeof import('./src/layouts/DefaultLayout.vue')['default']
    IconChevronRight: typeof import('./src/components/icons/IconChevronRight.vue')['default']
    IconEllipsisCircleOutline: typeof import('./src/components/icons/IconEllipsisCircleOutline.vue')['default']
    IconSearch: typeof import('./src/components/icons/IconSearch.vue')['default']
    NotFoundLayout: typeof import('./src/layouts/NotFoundLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VTab: typeof import('./src/components/base/tabs/VTab.vue')['default']
    VTabs: typeof import('./src/components/base/tabs/VTabs.vue')['default']
  }
}
