/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./../src/layouts/AppLayout.vue')['default']
    AppNavbar: typeof import('./../src/components/app/AppNavbar.vue')['default']
    AuctionLinks: typeof import('./../src/components/auction/AuctionLinks.vue')['default']
    DefaultLayout: typeof import('./../src/layouts/DefaultLayout.vue')['default']
    IconAdd: typeof import('./../src/components/icons/IconAdd.vue')['default']
    IconArrowNext: typeof import('./../src/components/icons/IconArrowNext.vue')['default']
    IconCamera: typeof import('./../src/components/icons/IconCamera.vue')['default']
    IconChevronRight: typeof import('./../src/components/icons/IconChevronRight.vue')['default']
    IconCloseCircle: typeof import('./../src/components/icons/IconCloseCircle.vue')['default']
    IconConfirmed: typeof import('./../src/components/icons/IconConfirmed.vue')['default']
    IconEllipsisCircleOutline: typeof import('./../src/components/icons/IconEllipsisCircleOutline.vue')['default']
    IconHeart: typeof import('./../src/components/icons/IconHeart.vue')['default']
    IconSearch: typeof import('./../src/components/icons/IconSearch.vue')['default']
    IconSelect: typeof import('./../src/components/icons/IconSelect.vue')['default']
    IconShare: typeof import('./../src/components/icons/IconShare.vue')['default']
    IconSorting: typeof import('./../src/components/icons/IconSorting.vue')['default']
    IconStar: typeof import('./../src/components/icons/IconStar.vue')['default']
    IconToken: typeof import('./../src/components/icons/IconToken.vue')['default']
    NotFoundLayout: typeof import('./../src/layouts/NotFoundLayout.vue')['default']
    NotWebAppButton: typeof import('./../src/components/base/NotWebAppButton.vue')['default']
    ProductCard: typeof import('./../src/components/store/ProductCard.vue')['default']
    Review: typeof import('./../src/components/store/Review.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VAlert: typeof import('./../src/components/base/VAlert.vue')['default']
    VBottomSheet: typeof import('./../src/components/base/VBottomSheet.vue')['default']
    VButton: typeof import('./../src/components/base/VButton.vue')['default']
    VInput: typeof import('./../src/components/base/VInput.vue')['default']
    VSelect: typeof import('./../src/components/base/VSelect.vue')['default']
    VTab: typeof import('./../src/components/base/tabs/VTab.vue')['default']
    VTabs: typeof import('./../src/components/base/tabs/VTabs.vue')['default']
  }
}
