/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'main': RouteRecordInfo<'main', '/', Record<never, never>, Record<never, never>>,
    '/__not-used-either/auction': RouteRecordInfo<'/__not-used-either/auction', '/__not-used-either/auction', Record<never, never>, Record<never, never>>,
    '/__not-used-either/auction/premium': RouteRecordInfo<'/__not-used-either/auction/premium', '/__not-used-either/auction/premium', Record<never, never>, Record<never, never>>,
    '/__not-used-either/auction/usernames': RouteRecordInfo<'/__not-used-either/auction/usernames', '/__not-used-either/auction/usernames', Record<never, never>, Record<never, never>>,
    'username': RouteRecordInfo<'username', '/__not-used-either/auction/usernames/:name', { name: ParamValue<true> }, { name: ParamValue<false> }>,
    'notFound': RouteRecordInfo<'notFound', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/market': RouteRecordInfo<'/market', '/market', Record<never, never>, Record<never, never>>,
    'market': RouteRecordInfo<'market', '/market', Record<never, never>, Record<never, never>>,
    '/market/store': RouteRecordInfo<'/market/store', '/market/store', Record<never, never>, Record<never, never>>,
    'categories': RouteRecordInfo<'categories', '/market/store/:id/categories', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'store': RouteRecordInfo<'store', '/market/store/:id/products', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'product': RouteRecordInfo<'product', '/market/store/:id/products/:productId', { id: ParamValue<true>, productId: ParamValue<true> }, { id: ParamValue<false>, productId: ParamValue<false> }>,
    'reviews': RouteRecordInfo<'reviews', '/market/store/:id/products/:productId/reviews', { id: ParamValue<true>, productId: ParamValue<true> }, { id: ParamValue<false>, productId: ParamValue<false> }>,
    '/user': RouteRecordInfo<'/user', '/user', Record<never, never>, Record<never, never>>,
    '/user/': RouteRecordInfo<'/user/', '/user', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/user/:id/profile', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'profileNotes': RouteRecordInfo<'profileNotes', '/user/:id/profile/notes', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'profileReviews': RouteRecordInfo<'profileReviews', '/user/:id/profile/reviews', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'account': RouteRecordInfo<'account', '/user/account', Record<never, never>, Record<never, never>>,
    'orders': RouteRecordInfo<'orders', '/user/account/orders', Record<never, never>, Record<never, never>>,
    'order': RouteRecordInfo<'order', '/user/account/orders/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'orderIssuing': RouteRecordInfo<'orderIssuing', '/user/account/orders/:id/issuing', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'accountSettings': RouteRecordInfo<'accountSettings', '/user/account/settings', Record<never, never>, Record<never, never>>,
    'createStore': RouteRecordInfo<'createStore', '/user/store/create', Record<never, never>, Record<never, never>>,
    '/user/store/info': RouteRecordInfo<'/user/store/info', '/user/store/info', Record<never, never>, Record<never, never>>,
    'storeInfo': RouteRecordInfo<'storeInfo', '/user/store/info', Record<never, never>, Record<never, never>>,
    'storeClients': RouteRecordInfo<'storeClients', '/user/store/info/clients', Record<never, never>, Record<never, never>>,
    'storeEmployers': RouteRecordInfo<'storeEmployers', '/user/store/info/employers', Record<never, never>, Record<never, never>>,
    '/user/store/info/orders': RouteRecordInfo<'/user/store/info/orders', '/user/store/info/orders', Record<never, never>, Record<never, never>>,
    'subscription': RouteRecordInfo<'subscription', '/user/store/subscription', Record<never, never>, Record<never, never>>,
  }
}
